CREATE TABLE  IF NOT EXISTS PRODUCTS(
product_id bigint(20) NOT NULL AUTO_INCREMENT,
product_desc varchar(50) NOT NULL,
PRIMARY KEY (product_id)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE  IF NOT EXISTS REVIEWS(
review_id bigint(20) NOT NULL AUTO_INCREMENT,
review_comment varchar(100) NOT NULL,
product_id bigint(20) NOT NULL,
PRIMARY KEY (review_id )
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;


CREATE TABLE  IF NOT EXISTS COMMENTS(
comment_id bigint(20) NOT NULL AUTO_INCREMENT,
comment varchar(100) NOT NULL,
review_id bigint(20) NOT NULL,
PRIMARY KEY (comment_id)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

ALTER TABLE COMMENTS ADD CONSTRAINT fk_review_id FOREIGN KEY (review_id) REFERENCES REVIEWS(review_id);
ALTER TABLE REVIEWS ADD CONSTRAINT fk_product_id FOREIGN KEY (product_id ) REFERENCES PRODUCTS(product_id );